theme: jekyll-theme-minimal
title: Myles McKay Data Science Portfolio
bio: I am astronomer pursuing data science roles to explore and preform descriptive and diagnostic analysis to multi and hyper spectral imaging
